export const allowedEmails = [
  "nandanaramachandran14@gmail.com",
  "Krishnabjsaikrishna@gmail.com",
  "fathimapajvad@gmail.com",
  "adwaid.s2007@gmail.com",
  "aswxnidas@gmail.com",
  "aksharasatheesh267@gmail.com",
  "harikrishnan19890@gmail.com",
  "ayishashan256@gmail.com",
  "catherinenixon1b30@gmail.com",
  "alwinsiby207@gmail.com",
  "avanirchandran14@gmail.com",
  "Joyal.studies@gmail.com",
  "Nith",
  "josephsijot1@gmail.com",
  "navaneethd2020@gmail.com",
  "abhilashr661@gmail.com",
  "suryandni4@gmail.com",
  "nsvarma2006@gmail.com",
  "jaisankarjayan3@gmail.com",
  "nehnasana@gmail.com",
  "unnineeraja810@gmail.com",
  "Nandanakb2307@gmail.com",
  "samuelfrancis2610@gmail.com",
  "sdevanarayanan017@gmail.com",
  "aswinanandpai250@gmail.com",
  "anamikaumesh03@gmail.com",
  "krishnapriyavr3@gmail.com",
  "sahalamariyam24@gmail.com",
  "sanakuriakose2005@gmail.com",
  "fiya1634@gmail.com",
  "niranjananayarath@gmail.com",
  "devanandacs56@gmail.com",
  "jopaulearaly123@gmail.com",
  "25bec472@adishankara.ac.in",
  "gayathrikv04444@gmail.com",
  "ramnadtrraj2436@gmail.com",
  "valsarajsarang9@gmail.com",
  "akshayamanoj96@gmail.com",
  "vyshnavpk780@gmail.com",
  "snavaneeth477@gmail.com",
  "1muhammedirfan0786@gmail.com",
  "hisniyamn123@gmail.com",
  "krishnanjanaushadharan@gmail.com",
  "kishancmcoco@gmail.com",
  "devups2005@gmail.com",
  "vasudevmenon777@gmail.com",
  "vaishnavms158@gmail.com",
  "dhanusreesunil008@gmail.com",
  "abhi",
  "madhav.j.century@gmail.com",
  "kedarajai6@gmail.com",
  "sridevib9965@gmail.com",
  "sridevi.nickyyy018@gmail.com",
  "ashilwright06@gmail.com",
  "rifasherin35@gmail.com",
  "navaneethsantosh74@gmail.com",
  "vish265wesh@gmail.com",
  "ameen.mehthab@gmail.com",
  "albin99mc@gmail.com",
  "anagha.ginesh@gmail.com",
  "adithyansunil0786@gmail.com",
  "navneetsanthosh14@gmail.com",
  "alexbaiju74@gmail.com",
  "Karthiksunil987@gmail.com",
  "sreesankarchittady@gmail.com",
  "thomassolomon906@gmail.com",
  "mahinsamad150@gmail.com",
  "georgejerin444@gmail.com",
  "namitha.nk39@gmail.com",
  "meenuks156@gmail.com",
  "ashutoshvmoff@gmail.com"
];

export const vibeCodingQuestions = [
  "Build a personal finance dashboard that tracks expenses and predicts future spending.",
  "Create an AI agent that summarizes long YouTube videos into actionable bullet points.",
  "Design a system for generating personalized workout plans based on user goals and equipment.",
  "Develop a tool that automatically organizes a messy downloads folder into categorized subfolders.",
  "Build a web app that generates custom bedtime stories for children featuring their name.",
  "Create a platform where users can practice job interviews with an AI recruiter.",
  "Design a smart recipe generator that suggests meals based on ingredients currently in the fridge.",
  "Develop a browser extension that blocks distracting websites during focus hours.",
  "Build a tool that converts handwritten notes into structured digital text and summaries.",
  "Create an AI-powered travel planner that creates detailed day-by-day itineraries.",
  "Design a system that analyzes a user's Spotify history and generates a unique music festival poster.",
  "Develop a web app that helps users learn a new language through interactive, AI-generated conversations.",
  "Build a tool that automatically generates flashcards from any uploaded PDF document.",
  "Create a platform for writers to get AI feedback on their short stories or novel chapters.",
  "Design a smart habit tracker that adjusts its reminders based on the user's past behavior.",
  "Develop a web app that generates custom, printable board games based on user themes.",
  "Build an AI agent that monitors flight prices and alerts the user when a good deal is found.",
  "Create a tool that helps users practice public speaking by analyzing their tone and pacing.",
  "Design a system that automatically creates a weekly meal prep grocery list.",
  "Develop a web app that generates personalized poetry based on a user's mood and keywords.",
  "Build a platform where users can create and share interactive, AI-generated text adventures.",
  "Create a tool that analyzes a user's resume and suggests improvements for specific job postings.",
  "Design a smart calendar that automatically schedules tasks based on priority and estimated time.",
  "Develop a web app that generates custom coloring book pages from user prompts.",
  "Build an AI agent that helps users negotiate better deals on their monthly bills.",
  "Create a platform for generating custom, AI-composed background music for focus or relaxation.",
  "Design a system that analyzes a user's wardrobe and suggests daily outfits based on the weather.",
  "Develop a web app that helps users plan and track their indoor plant care routines.",
  "Build a tool that automatically generates a personal portfolio website from a user's LinkedIn profile.",
  "Create an AI-powered tutor that helps students understand complex math concepts step-by-step.",
  "Design a smart journaling app that prompts users with reflective questions based on their previous entries.",
  "Develop a web app that generates custom, 3D-printable models from simple sketches.",
  "Build a platform where users can create and share AI-generated comic strips.",
  "Create a tool that analyzes a user's reading habits and suggests their next book.",
  "Design a system that automatically creates a personalized daily news briefing.",
  "Develop a web app that helps users plan and organize their next home renovation project.",
  "Build an AI agent that helps users find and apply for relevant scholarships or grants.",
  "Create a platform for generating custom, AI-designed logos and branding materials.",
  "Design a smart budget tracker that gamifies saving money.",
  "Develop a web app that generates personalized meditation sessions based on user stress levels.",
  "Build a tool that automatically summarizes long email threads and highlights action items.",
  "Create an AI-powered interior design assistant that suggests furniture arrangements.",
  "Design a system that analyzes a user's sleep patterns and suggests improvements.",
  "Develop a web app that helps users plan and track their marathon training.",
  "Build a platform where users can create and share AI-generated interactive quizzes.",
  "Create a tool that analyzes a user's coding style and suggests improvements.",
  "Design a smart shopping list that automatically categorizes items by store aisle.",
  "Develop a web app that generates custom, AI-narrated audiobooks from public domain texts.",
  "Build an AI agent that helps users plan and organize their next vacation.",
  "Create a platform for generating custom, AI-designed greeting cards.",
  "Design a system that analyzes a user's diet and suggests nutritional improvements.",
  "Develop a web app that helps users plan and track their daily water intake.",
  "Build a tool that automatically generates a personalized study schedule for exams.",
  "Create an AI-powered personal stylist that suggests outfits based on current trends.",
  "Design a smart task manager that uses the Pomodoro technique.",
  "Develop a web app that generates custom, AI-composed lullabies for babies.",
  "Build a platform where users can create and share AI-generated short films.",
  "Create a tool that analyzes a user's social media presence and suggests improvements.",
  "Design a system that automatically creates a personalized weekly workout routine.",
  "Develop a web app that helps users plan and organize their next dinner party.",
  "Build an AI agent that helps users find and book the best local restaurants.",
  "Create a platform for generating custom, AI-designed tattoos.",
  "Design a smart expense tracker that automatically categorizes purchases.",
  "Develop a web app that generates personalized yoga routines based on user flexibility.",
  "Build a tool that automatically summarizes long articles and highlights key points.",
  "Create an AI-powered personal chef that suggests recipes based on dietary restrictions.",
  "Design a system that analyzes a user's productivity and suggests improvements.",
  "Develop a web app that helps users plan and track their daily steps.",
  "Build a platform where users can create and share AI-generated interactive stories.",
  "Create a tool that analyzes a user's writing style and suggests improvements.",
  "Design a smart grocery list that automatically suggests items based on past purchases.",
  "Develop a web app that generates custom, AI-composed ringtones.",
  "Build an AI agent that helps users find and book the best local events.",
  "Create a platform for generating custom, AI-designed clothing.",
  "Design a system that analyzes a user's fitness level and suggests improvements.",
  "Develop a web app that helps users plan and organize their next road trip.",
  "Build a tool that automatically generates a personalized daily schedule.",
  "Create an AI-powered personal trainer that suggests exercises based on user goals.",
  "Design a smart habit tracker that uses gamification to encourage consistency.",
  "Develop a web app that generates personalized mindfulness exercises based on user mood.",
  "Build a platform where users can create and share AI-generated interactive games.",
  "Create a tool that analyzes a user's learning style and suggests improvements.",
  "Design a system that automatically creates a personalized weekly meal plan.",
  "Develop a web app that helps users plan and organize their next camping trip.",
  "Build an AI agent that helps users find and book the best local activities.",
  "Create a platform for generating custom, AI-designed jewelry.",
  "Design a smart budget tracker that automatically suggests areas to save money.",
  "Develop a web app that generates personalized stretching routines based on user activity.",
  "Build a tool that automatically summarizes long podcasts and highlights key points.",
  "Create an AI-powered personal shopper that suggests items based on user preferences.",
  "Design a system that analyzes a user's mental health and suggests improvements.",
  "Develop a web app that helps users plan and track their daily meditation.",
  "Build a platform where users can create and share AI-generated interactive art.",
  "Create a tool that analyzes a user's communication style and suggests improvements.",
  "Design a smart grocery list that automatically suggests items based on sales.",
  "Develop a web app that generates custom, AI-composed soundscapes.",
  "Build an AI agent that helps users find and book the best local services.",
  "Create a platform for generating custom, AI-designed furniture.",
  "Design a system that analyzes a user's environmental impact and suggests improvements.",
  "Develop a web app that helps users plan and organize their next volunteer project."
];
